version: '3.8'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.118.0
    container_name: otel-collector
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: --config /etc/otel-collector-config.yaml
    depends_on:
      - prometheus
      - loki
      - tempo
#      - jaeger

  # Jaeger
#  jaeger:
#    image: jaegertracing/all-in-one:1.65.0
#    container_name: jaeger
#    ports:
#      - "16686:16686"  # Jaeger UI
#      - "14250:14250"  # Jaeger gRPC
#    # environment:
#    #   - SPAN_STORAGE_TYPE=badger
#    #   - BADGER_EPHEMERAL=false
#    #   - BADGER_DIRECTORY_VALUE=/badger/data
#    #   - BADGER_DIRECTORY_KEY=/badger/key
#    volumes:
#      - jaeger-data:/badger

  tempo:
    image: grafana/tempo:2.6.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo-config.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo-config.yaml

  # Prometheus
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    ports:
      - "9090:9090"  # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=30d # 配置存储中的数据保留时间
      - --storage.tsdb.retention.size=10GB
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms

  # Loki
  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    ports:
      - "3100:3100"  # Loki API
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  # Grafana
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo
#      - jaeger

  mysql:
    image: mysql:8.0.34
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper



volumes:
#  jaeger-data:
  grafana-storage: