auth_enabled: false

server:
  http_listen_port: 3100

## 专用于接收处理OTEL数据
limits_config:
  allow_structured_metadata: true
  volume_enabled: true

common:
  path_prefix: /tmp/loki
  replication_factor: 1
  instance_addr: 0.0.0.0
  ring:
    kvstore:
      store: inmemory

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
  filesystem:
    directory: /tmp/loki/chunks

pattern_ingester:
  enabled: true

compactor:
  retention_enabled: true
  retention_delete_delay: 720h # 24h*30=720h
  delete_request_store: filesystem

schema_config:
  configs:
    - from: 2024-10-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: otlp_
        period: 24h # 24h*30=720h