receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # gRPC 端口
      http:
        endpoint: "0.0.0.0:4318"  # HTTP 端口

exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
#  prometheus:
#    endpoint: "0.0.0.0:9090"
#  otlp/jaeger:
#    endpoint: "jaeger:4317"
#    tls:
#      insecure: true
#  otlphttp/loki:
#    endpoint: "http://loki:3100/otlp"
#    tls:
#      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
#      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
#      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
#      exporters: [otlphttp/loki]