receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # gRPC 端口
      http:
        endpoint: "0.0.0.0:4318"  # HTTP 端口

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9090"
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]